name: split_screen
description: Foldable and dual-screen support, like the TwoPane widget and hinge angle sensor data. Forked from the Microsoft dual_screen package.
version: 1.0.5
homepage: https://docs.microsoft.com/en-us/dual-screen/
repository: https://github.com/DeekFit/flutter-splitscreen

environment:
  sdk: ">=2.12.0 < 4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.microsoft.flutterdualscreen
        pluginClass: DualScreenInfo